name: Deploy to DigitalOcean Container Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v1

    # - name: Login To DigitalOcean Container Registry
    #   uses: docker/login-action@v1
    #   with:
    #     registry: registry.digitalocean.com
    #     username: ${{ secrets.DIGITALOCEAN_ACCESS_KEY }}
    #     password: ${{ secrets.DIGITALOCEAN_SECRET_KEY }}

    # - name: Install Doctl
    #   run: |
    #     curl -sL https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar -xzv
    #     sudo mv doctl /usr/local/bin
    #     doctl version

    # - name: Configure Doctl
    #   run: doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_KEY }}

    # - name: Delete Latest Container Image
    #   run: doctl registry repository delete-tag --force registry.digitalocean.com/naads-alerts/naads-alert-server latest

    # - name: Build And Push Docker Image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: registry.digitalocean.com/naads-alerts/naads-alert-server:latest

    # - name: Set Up Terraform, Plan & Apply
    #   uses: hashicorp/setup-terraform@v2
    #   with:
    #     terraform_version: 1.1.7

    # - name: Terraform Init
    #   run: cd terraform && terraform init

    # - name: Terraform Plan
    #   run: cd terraform && terraform plan -var="do_token=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" -var="node_env=${{ secrets.NODE_ENV }}" -var="mongo_uri=${{ secrets.MONGO_URI }}" -var="redis_url=${{ secrets.REDIS_URL }}" -var="jwt_secret=${{ secrets.JWT_SECRET }}" -var="api_version=${{ secrets.API_VERSION }}"

    # - name: Terraform Apply
    #   run: cd terraform && terraform apply -auto-approve -var="do_token=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" -var="node_env=${{ secrets.NODE_ENV }}" -var="mongo_uri=${{ secrets.MONGO_URI }}" -var="redis_url=${{ secrets.REDIS_URL }}" -var="jwt_secret=${{ secrets.JWT_SECRET }}" -var="api_version=${{ secrets.API_VERSION }}"
